[package]
name = "ossia-sys"
version = "0.1.1"
authors = ["Alex Norman <alex@x37v.info>"]
edition = "2018"
license = "CeCILL-C FREE SOFTWARE LICENSE AGREEMENT"

[build-dependencies]
cmake = "0.1.42"
bindgen = "0.53.2"
